emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
  lifecycle:
    biomass:
      datetime: '2014-01-01'
      source: IPCC 2014; BEIS 2021
      value: 230.0
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
flag_file_name: li.png
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: Europe/Vaduz
